### ISSUE TITLE
Testing on a windows touchscreen device

### ISSUE THREAD

**Issue by blaise17** [eQualityTime/ovfplayer#127]
We need to test the app on a windows touchscreen device, especially for the new button trigger event behaviour config.
But we need to get one first...

**Comment by joereddington-public** [comment]
How about this one: https://www.amazon.co.uk/Windows-Fusion5-FWIN232-quad-core-Bluetooth/dp/B00YCX7SGU/ref=sr_1_5?ie=UTF8&qid=1549973606&sr=8-5&keywords=windows+tablet

**Comment by psi77** [comment]
That would be perfect
