### ISSUE TITLE
Does not handle missing online images well

### ISSUE THREAD

**Issue by blaise17** [eQualityTime/ovfplayer#135]
If a board loads an external image through url and that image is not there there is no feedback to the user and the board breaks in odd ways

**Comment by joereddington** [comment]
Here's a test obf file for the situation: https://joereddington.com/imagelinkbroken.obf

**Comment by blaise17** [comment]
https://dl.dropboxusercontent.com/s/6gf988tggpoff69/imagelinkbroken.obf?dl=1
