### ISSUE TITLE
"Capital I" 

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/ovfplayer#137]
This message window contents: 
![screenshot 2019-02-13 11 30 20](https://user-images.githubusercontent.com/4369547/52708769-ee31b600-2f82-11e9-8b0b-f0fc80fc3379.png)

...is vocalised as "Capital I"  it should be vocalised as "I".

(On firefox)

**Comment by psi77** [comment]
It doesn't seem to do this in Chrome. 
What browser are you using?
Does it do it if 'I' is followed by other utterances?

**Comment by joereddington** [comment]
Yep - firefox, doesn't do it as part of a longer sentence : (

**Comment by psi77** [comment]
Is that less of a problem then?
It's possibly going to be tricky to fix

**Comment by joereddington** [comment]
It's definitely a problem - particularly if they have 'speak each word' flag on.   Is it one of those situations were we have to insert silly characters?

**Comment by psi77** [comment]
Yeah, it may have to be silly characters

**Comment by psi77** [comment]
Hahaha it doesn't do it on firefox on windows :-D

**Comment by psi77** [comment]
It seems to be a mac thing.
It does it on chrome and safari on an iPad.
They both use the same speech engine so that's probably where the problem lies

**Comment by psi77** [comment]
Whilst fixing this it caused some problems with 'No' being pronounced as 'Number' (due to the addition of a period)
Also empty speech bar was causing a problem.
Should all be fixed now, but thought I'd mention it for testing notes!
