### ISSUE TITLE
Need a way to access config from installed pwa

### ISSUE THREAD

**Issue by psi77** [eQualityTime/ovfplayer#32]
<a href="https://github.com/psi77"><img src="https://avatars1.githubusercontent.com/u/26653703?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [psi77](https://github.com/psi77)**
_Friday Nov 16, 2018 at 16:56 GMT_
_Originally opened as https://github.com/eQualityTime/Pageset-Reader/issues/32_

----

An installed pwa doesn't show the url bar and so there would be no way to get to config. It may be that the installed version would share local storage with the web version and so users could go to their browser to access config. But this seems a bit icky

**Comment by psi77** [comment]
It's possible that config is shared between the installed PWA and accessing the app from a browser.  In which case.....configuration can easily be achieved by visiting the app in a browser and changing config

**Comment by psi77** [comment]
Looks like the config is indeed shared between the installed PWA and the browser.  So config can be simply accessed from the browser.

Will this do for now?

**Comment by blaise17** [comment]
Sounds good to me

**Comment by blaise17** [comment]
@joereddington ?

**Comment by joereddington** [comment]
Hmmmm.   

Hmmmm.  

Firstly, I don't know enough about this to have a *proper* opinion.  But, assuming that 'browser' doesn't imply 'internet', then I think leaving it in the browser is cool (there are bunch of ways you would want to change settings while out and about, particularly at weddings) 

Does that make sense?

**Comment by psi77** [comment]
@joereddington I think that makes sense. We need to address the issue of the config page always trying to reload the selected page when save is pressed. But I believe that's part of another ticket

**Comment by blaise17** [comment]
It is part of issue #91
