### ISSUE TITLE
Need different favicon.ico

### ISSUE THREAD

**Issue by psi77** [eQualityTime/ovfplayer#52]
<a href="https://github.com/psi77"><img src="https://avatars1.githubusercontent.com/u/26653703?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [psi77](https://github.com/psi77)**
_Saturday Nov 17, 2018 at 16:13 GMT_
_Originally opened as https://github.com/eQualityTime/Pageset-Reader/issues/52_

----

The current favicon is the angular icon.
Should have an open voice factory icon.
Whilst we're here we should probably change the html title to 'Open Voice Factory' (with spaces, it is currently camel cased)

**Comment by psi77** [comment]
@joereddington would you be able to look at this ticket and get us an appropriate open voice factory or eQualityTime icon?

**Comment by joereddington** [comment]
![icon-16](https://user-images.githubusercontent.com/4369547/49080170-ad0aef00-f23a-11e8-9dd1-1dad8c2412ed.png)
Equality Time icon attached.  We also have some funds availible to get a proper logo for OVF designed. But probably better to use the EQT for now?

**Comment by psi77** [comment]
Yeah, anything will be better than the current angular icon!
Thank you!
