### ISSUE TITLE
Implement scanning

### ISSUE THREAD

**Issue by psi77** [eQualityTime/ovfplayer#55]
<a href="https://github.com/psi77"><img src="https://avatars1.githubusercontent.com/u/26653703?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [psi77](https://github.com/psi77)**
_Saturday Nov 17, 2018 at 20:03 GMT_
_Originally opened as https://github.com/eQualityTime/Pageset-Reader/issues/55_

----

![whatsapp video 2018-11-17 at 19 47 02](https://user-images.githubusercontent.com/26653703/48665413-a398be80-eaa5-11e8-9f1a-17582ad1216e.gif)

**Comment by psi77** [comment]
Config option for scanning speed?

**Comment by joereddington** [comment]
Would be useful - even if there weren't different abilities - users get used to it and get faster.  

FWIW - scanning is one of those areas with lots of different methods and customisations including two button (one button moves forward in the sequence, the other activates), other sequences (such as 'one-by-one' or zone-by-zone, or check-with-the-message-window-after-every-completed-row) and probably some I'm struggling to bring to mind. So it might be that this is going to be code that gets re-written a lot...

**Comment by blaise17** [comment]
So far we're assuming that users that need scanning are not going to be turning it on and off frequently and so we're planning to make scanning a config option (and probably a set of config options later).
Is that okay?

**Comment by blaise17** [comment]
We plan to implement the row then cell scanning, witht he speechbar component being the first row.
