### ISSUE TITLE
Breadcrumbs

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/ovfplayer#97]
From user interview, 

We would like a button, appearing at the extreme right of the message window, that returns the user to the previous page.  This is useful for learning the pageset, particularly in a group: 

* "How did you get there?" 
* *presses back* 
* "Oh, it's a type of sport" 

The user's mental model for this is a stack - pages that are reached by using 'normal' jump-to-page actions are added to the stack, the back button pops entries from the stack. 

There is a potential optimisation - which is that the back button takes the shortest path back from that page in the history to the root.  I think that's an unexpected behaviour, but the THING to do is to ask the user: 

For the back button - what do you think the back button should do if a user has gone round in a loop a lot for fun? 

Assuming the user has gone to the following pages: 
Root-->food-->flavours-->food-->flavours-->food-->flavours-->food-->flavours-->food-->flavours-->food-->flavours-->food and is now on 'food'.

Should the back button: 

- Unwind the loop repeatedly (jump to every link in the chain)
- Unwind the loop once and then take a shortcut out (jump to flavours then food then root) 
- Immediately take the shortest rout back (jump directly to root from food)

**Comment by psi77** [comment]
I think we can very simply implement full stack back button and the shortcut options and make them behaviours that can be chosen by config.  So we should probably just do all of them!

**Comment by joereddington-public** [comment]
This pairs up nicely with the pull request that's gone through because it's for the same end-user...
